[package]
name = "rsu"
version = "0.1.0"
authors = ["luxiang.zhou <luxiang.zhou@autocore.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
