name: ci

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REPO: https://github.com/${{ github.repository }}
  IMG_NAME: ghcr.io/${{ github.repository }}::${GITHUB_REF#refs/heads/}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Set up QEMU
      if: success() && github.event_name != 'pull_request'
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      if: success() && github.event_name != 'pull_request'
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      if: success() && github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      if: success() && github.event_name != 'pull_request'
      run: |
            docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --build-arg REPO=${{ env.REPO }} \
            --tag ${{ env.IMG_NAME }} \
            --file ./Dockerfile .
