name: ci

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REPO: https://github.com/${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Build
      run: cargo build --verbose
    -
      name: Run tests
      run: cargo test --verbose

  docker:
    needs: [test]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      run: |
            echo $((echo "ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/heads/}" ) | tr '[:upper:]' '[:lower:]') >> $DOCKER_IMAGE
            docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --build-arg REPO=${{ env.REPO }} \
            --tag $DOCKER_IMAGE \
            --file Dockerfile .
